name: 'Go Feature Flag Lint Action'
description: 'Lint Go Feature Flag Config stored in a repository'
inputs:
  flag-file:
    required: false
    description: "The path to the GO Feature Flag configuration to lint"
    default: "flag-config.yaml"
  format:
    required: false
    description: "The format of the file to lint (yaml, json, toml)"
    default: "yaml"
outputs:
  lint-message:
    description: "Reads the result of the linting step"
    value: ${{ steps.lint.outputs.lint-message }}
runs:
  using: "docker"
  image: "docker://thomaspoignant/go-feature-flag-lint:v1"
  volumes:
    - ${{ github.workspace }}:/github_workspace
  args:
    - --input-format=${{ inputs.format }}
    - --input-file=/github_workspace/${{ inputs.flag-file }}